timepiece/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    # Redirect the base URL to the dashboard.
    url(r'^$', RedirectView.as_view(url=reverse_lazy('dashboard'), permanent=False)),

    url('', include('timepiece.crm.urls')),
    url('', include('timepiece.contracts.urls')),
    url('', include('timepiece.entries.urls')),
    url('', include('timepiece.reports.urls')),
]

timepiece/crm/models.py
from collections import OrderedDict

from django.apps import apps
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models

from timepiece.utils import get_active_entry


# Add a utility method to the User class that will tell whether or not a
# particular user has any unclosed entries
_clocked_in = lambda user: bool(get_active_entry(user))
User.add_to_class('clocked_in', property(_clocked_in))


# Utility method to get user's name, falling back to username.
_get_name_or_username = lambda user: user.get_full_name() or user.username
User.add_to_class('get_name_or_username', _get_name_or_username)


_get_absolute_url = lambda user: reverse('view_user', args=(user.pk,))
User.add_to_class('get_absolute_url', _get_absolute_url)


class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True, related_name='profile', on_delete=models.deletion.CASCADE)
    hours_per_week = models.DecimalField(
        max_digits=8, decimal_places=2, default=40)

    class Meta:
        db_table = 'timepiece_userprofile'  # Using legacy table name.

    def __str__(self):
        return self.user


class TypeAttributeManager(models.Manager):
    """Object manager for type attributes."""

    def get_queryset(self):
        qs = super(TypeAttributeManager, self).get_queryset()
        return qs.filter(type=Attribute.PROJECT_TYPE)


class StatusAttributeManager(models.Manager):
    """Object manager for status attributes."""

    def get_queryset(self):
        qs = super(StatusAttributeManager, self).get_queryset()
        return qs.filter(type=Attribute.PROJECT_STATUS)


class Attribute(models.Model):
    PROJECT_TYPE = 'project-type'
    PROJECT_STATUS = 'project-status'
    ATTRIBUTE_TYPES = OrderedDict((
        (PROJECT_TYPE, 'Project Type'),
        (PROJECT_STATUS, 'Project Status'),
    ))
    SORT_ORDER_CHOICES = [(x, x) for x in range(-20, 21)]

    type = models.CharField(max_length=32, choices=ATTRIBUTE_TYPES.items())
    label = models.CharField(max_length=255)
    sort_order = models.SmallIntegerField(
        null=True, blank=True, choices=SORT_ORDER_CHOICES)
    enable_timetracking = models.BooleanField(
        default=False,
        help_text=('Enable time tracking functionality for projects '
                   'with this type or status.'))
    billable = models.BooleanField(default=False)

    objects = models.Manager()
    types = TypeAttributeManager()
    statuses = StatusAttributeManager()

    class Meta:
        db_table = 'timepiece_attribute'  # Using legacy table name.
        unique_together = ('type', 'label')
        ordering = ('sort_order',)

    def __str__(self):
        return self.label


class Business(models.Model):
    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=255, blank=True)
    email = models.EmailField(blank=True)
    description = models.TextField(blank=True)
    notes = models.TextField(blank=True)
    external_id = models.CharField(max_length=32, blank=True)

    class Meta:
        db_table = 'timepiece_business'  # Using legacy table name.
        ordering = ('name',)
        verbose_name_plural = 'Businesses'

    def __str__(self):
        return self.get_display_name()

    def get_absolute_url(self):
        return reverse('view_business', args=(self.pk,))

    def get_display_name(self):
        return self.short_name or self.name


class TrackableProjectManager(models.Manager):

    def get_queryset(self):
        return super(TrackableProjectManager, self).get_queryset().filter(
            status__enable_timetracking=True,
            type__enable_timetracking=True,
        )


class Project(models.Model):
    name = models.CharField(max_length=255)
    tracker_url = models.CharField(
        max_length=255, blank=True, null=False, default="")
    business = models.ForeignKey(
        Business, related_name='new_business_projects', on_delete=models.deletion.CASCADE)
    point_person = models.ForeignKey(User, limit_choices_to={'is_staff': True}, on_delete=models.deletion.CASCADE)
    users = models.ManyToManyField(
        User, related_name='user_projects', through='ProjectRelationship')
    activity_group = models.ForeignKey(
        'entries.ActivityGroup', related_name='activity_group', null=True,
        blank=True, verbose_name='restrict activities to', on_delete=models.deletion.CASCADE)
    type = models.ForeignKey(
        Attribute, limit_choices_to={'type': 'project-type'},
        related_name='projects_with_type', on_delete=models.deletion.CASCADE)
    status = models.ForeignKey(
        Attribute, limit_choices_to={'type': 'project-status'},
        related_name='projects_with_status', on_delete=models.deletion.CASCADE)
    description = models.TextField()

    objects = models.Manager()
    trackable = TrackableProjectManager()

    class Meta:
        db_table = 'timepiece_project'  # Using legacy table name.
        ordering = ('name', 'status', 'type',)
        permissions = (
            ('email_project_report', 'Can email project report'),
            ('view_project_time_sheet', 'Can view project time sheet'),
            ('export_project_time_sheet', 'Can export project time sheet'),
            ('generate_project_invoice', 'Can generate project invoice'),
        )

    def __str__(self):
        return '{0} ({1})'.format(self.name, self.business.get_display_name())

    @property
    def billable(self):
        return self.type.billable

    def get_absolute_url(self):
        return reverse('view_project', args=(self.pk,))

    def get_active_contracts(self):
        """Returns all associated contracts which are not marked complete."""
        ProjectContract = apps.get_model('contracts', 'ProjectContract')
        return self.contracts.exclude(status=ProjectContract.STATUS_COMPLETE)


class RelationshipType(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255)

    class Meta:
        db_table = 'timepiece_relationshiptype'  # Using legacy table name.

    def __str__(self):
        return self.name


class ProjectRelationship(models.Model):
    types = models.ManyToManyField(
        RelationshipType, blank=True, related_name='project_relationships')
    user = models.ForeignKey(User, related_name='project_relationships', on_delete=models.deletion.CASCADE)
    project = models.ForeignKey(Project, related_name='project_relationships', on_delete=models.deletion.CASCADE)

    class Meta:
        db_table = 'timepiece_projectrelationship'  # Using legacy table name.
        unique_together = ('user', 'project')

    def __str__(self):
        return "{project}'s relationship to {user}".format(
            project=self.project.name,
            user=self.user.get_name_or_username(),
        )

timepiece/contracts/views.py
import datetime
from dateutil.relativedelta import relativedelta

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.urls import reverse
from django.db import transaction, DatabaseError
from django.db.models import Sum, Q
from django.db.models.expressions import F, Func, Value
from django.http import HttpResponseRedirect, Http404, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView, DetailView

from timepiece import utils
from timepiece.templatetags.timepiece_tags import seconds_to_hours
from timepiece.utils.csv import CSVViewMixin
from timepiece.utils.search import SearchListView
from timepiece.utils.views import cbv_decorator

from timepiece.contracts.forms import InvoiceForm, OutstandingHoursFilterForm
from timepiece.contracts.models import ProjectContract, HourGroup, EntryGroup
from timepiece.entries.models import Project, Entry


@cbv_decorator(permission_required('contracts.add_projectcontract'))
class ContractDetail(DetailView):
    template_name = 'timepiece/contract/view.html'
    model = ProjectContract
    context_object_name = 'contract'
    pk_url_kwarg = 'contract_id'

    def get_context_data(self, *args, **kwargs):
        if 'today' not in kwargs:
            kwargs['today'] = datetime.date.today()
        if 'warning_date' not in kwargs:
            kwargs['warning_date'] = datetime.date.today() + relativedelta(weeks=2)
        return super(ContractDetail, self).get_context_data(*args, **kwargs)


@cbv_decorator(permission_required('contracts.add_projectcontract'))
class ContractList(ListView):
    template_name = 'timepiece/contract/list.html'
    model = ProjectContract
    context_object_name = 'contracts'
    queryset = ProjectContract.objects.filter(
        status=ProjectContract.STATUS_CURRENT).order_by('name')

    def get_context_data(self, *args, **kwargs):
        if 'today' not in kwargs:
            kwargs['today'] = datetime.date.today()
        if 'warning_date' not in kwargs:
            kwargs['warning_date'] = datetime.date.today() + relativedelta(weeks=2)
        kwargs['max_work_fraction'] = max(
            [0.0] + [c.fraction_hours for c in self.queryset.all()])
        kwargs['max_schedule_fraction'] = max(
            [0.0] + [c.fraction_schedule for c in self.queryset.all()])
        kwargs['projects_pending'] = ProjectContract.objects.filter(
            status=ProjectContract.STATUS_UPCOMING).order_by('name')
        kwargs['projects_complete'] = ProjectContract.objects.filter(
            status=ProjectContract.STATUS_COMPLETE).order_by('name')
        return super(ContractList, self).get_context_data(*args, **kwargs)


@login_required
@transaction.atomic
def create_invoice(request):
    pk = request.GET.get('project', None)
    to_date = request.GET.get('to_date', None)
    if not (pk and to_date):
        raise Http404
    from_date = request.GET.get('from_date', None)
    if not request.user.has_perm('crm.generate_project_invoice'):
        return HttpResponseForbidden('Forbidden')
    try:
        to_date = utils.add_timezone(
            datetime.datetime.strptime(to_date, '%Y-%m-%d'))
        if from_date:
            from_date = utils.add_timezone(
                datetime.datetime.strptime(from_date, '%Y-%m-%d'))
    except (ValueError, OverflowError):
        raise Http404
    project = get_object_or_404(Project, pk=pk)
    initial = {
        'project': project,
        'user': request.user,
        'from_date': from_date,
        'to_date': to_date,
    }
    entries_query = {
        'status': Entry.APPROVED,
        'end_time__lt': to_date + relativedelta(days=1),
        'project__id': project.id
    }
    if from_date:
        entries_query.update({'end_time__gte': from_date})
    invoice_form = InvoiceForm(request.POST or None, initial=initial)
    if request.POST and invoice_form.is_valid():
        entries = Entry.no_join.filter(**entries_query)
        if entries.exists():
            # LOCK the entries until our transaction completes - nobody
            # else will be able to lock or change them - see
            # https://docs.djangoproject.com/en/1.4/ref/models/querysets/#select-for-update
            # (This feature requires Django 1.4.)
            # If more than one request is trying to create an invoice from
            # these same entries, then the second one to get to this line will
            # throw a DatabaseError.  That can happen if someone double-clicks
            # the Create Invoice button.
            try:
                entries.select_for_update(nowait=True)
            except DatabaseError:
                # Whoops, we lost the race
                messages.add_message(request, messages.ERROR,
                                     "Lock error trying to get entries")
            else:
                # We got the lock, we can carry on
                invoice = invoice_form.save()
                Entry.no_join.filter(pk__in=entries).update(
                    status=invoice.status, entry_group=invoice)
                messages.add_message(request, messages.INFO,
                                     "Invoice created")
                return HttpResponseRedirect(reverse('view_invoice',
                                                    args=[invoice.pk]))
        else:
            messages.add_message(request, messages.ERROR,
                                 "No entries for invoice")
    else:
        entries = Entry.objects.filter(**entries_query)
        entries = entries.order_by('start_time')
        if not entries:
            raise Http404

    billable_entries = entries.filter(activity__billable=True) \
        .select_related()
    nonbillable_entries = entries.filter(activity__billable=False) \
        .select_related()
    return render(request, 'timepiece/invoice/create.html', {
        'invoice_form': invoice_form,
        'billable_entries': billable_entries,
        'nonbillable_entries': nonbillable_entries,
        'project': project,
        'billable_totals': HourGroup.objects.summaries(billable_entries),
        'nonbillable_totals': HourGroup.objects.summaries(nonbillable_entries),
        'from_date': from_date,
        'to_date': to_date,
    })


@permission_required('contracts.change_entrygroup')
def list_outstanding_invoices(request):
    form = OutstandingHoursFilterForm(request.GET or None)
    # Determine the query to make based on the form
    if form.is_valid() or not form.is_bound:
        form_data = form.get_form_data()
        # Adjust to_date so the query includes all of the last day
        to_date = form_data['to_date'] + relativedelta(days=1)
        from_date = form_data['from_date']
        statuses = form_data['statuses']
        dates = Q()
        dates &= Q(end_time__gte=from_date) if from_date else Q()
        dates &= Q(end_time__lt=to_date) if to_date else Q()
        billable = Q(project__type__billable=True, project__status__billable=True)
        entry_status = Q(status=Entry.APPROVED)
        project_status = Q(project__status__in=statuses) if statuses is not None else Q()
        # Calculate hours for each project
        ordering = ('project__type__label', 'project__status__label',
                    'project__business__name', 'project__name', 'status')
        project_totals = Entry.objects.filter(
            dates, billable, entry_status, project_status).order_by(*ordering)
        # Find users with unverified/unapproved entries to warn invoice creator
        date_range_entries = Entry.objects.filter(dates)
        user_values = ['user__pk', 'user__first_name', 'user__last_name']
        unverified = date_range_entries.filter(status=Entry.UNVERIFIED)
        unverified = unverified.values_list(*user_values).order_by('user__first_name').distinct()
        unapproved = date_range_entries.filter(status=Entry.VERIFIED)
        unapproved = unapproved.values_list(*user_values).order_by('user__first_name').distinct()
    else:
        project_totals = unverified = unapproved = Entry.objects.none()
    return render(request, 'timepiece/invoice/outstanding.html', {
        'date_form': form,
        'project_totals': project_totals,
        'unverified': unverified,
        'unapproved': unapproved,
        'to_date': form.get_to_date(),
        'from_date': form.get_from_date(),
    })


@cbv_decorator(permission_required('contracts.add_entrygroup'))
class ListInvoices(SearchListView):
    model = EntryGroup
    paginate_by = 20
    search_fields = ['user__username__icontains', 'project__name__icontains',
                     'comments__icontains', 'number__icontains']
    template_name = 'timepiece/invoice/list.html'

    def get_queryset(self):
        qs = super(ListInvoices, self).get_queryset()
        return qs.order_by('-end', '-id')


@cbv_decorator(permission_required('contracts.change_entrygroup'))
class InvoiceDetail(DetailView):
    template_name = 'timepiece/invoice/view.html'
    model = EntryGroup
    context_object_name = 'invoice'
    pk_url_kwarg = 'invoice_id'

    def get_context_data(self, **kwargs):
        context = super(InvoiceDetail, self).get_context_data(**kwargs)
        invoice = context['invoice']
        billable_entries = invoice.entries.filter(activity__billable=True)\
                                          .order_by('start_time')\
                                          .select_related()
        nonbillable_entries = invoice.entries.filter(activity__billable=False)\
                                             .order_by('start_time')\
                                             .select_related()
        return {
            'invoice': invoice,
            'billable_entries': billable_entries,
            'billable_totals': HourGroup.objects
                                        .summaries(billable_entries),
            'nonbillable_entries': nonbillable_entries,

timepiece/templates/timepiece/invoice/_edit_entry_list.html
{% load timepiece_tags %}
<table class="table table-bordered table-condensed">
    <tr>
        <th>Date</th>
        <th>User</th>
        <th>Time</th>
        <th>Project</th>
        <th>Activity</th>
        <th>Hours</th>
        <th>Comments</th>
        <th>Remove</th>
    </tr>
    {% for entry in entries %}
        {% ifchanged entry.start_time|date:"W" %}
            <tr class="ledger_header">
                <th colspan='8'>Week of {{ entry.start_time|week_start|date }} </th>
            </tr>
        {% endifchanged %}
        <tr>
            {% ifchanged entry.start_time|date %}
                <td>{{ entry.start_time|date:"m/d/Y (D)" }}</td>
            {% else %}
                <td></td>
            {% endifchanged %}
            <td>{{ entry.user.get_name_or_username }} </td>
            <td>{{ entry.start_time|time }} - {{ entry.end_time|time }} </td>
            <td>{{ entry.project.name }}</td>
            <td>{{ entry.activity.name }}</td>
            <td class="hours">{{ entry.hours }}</td>
            <td title="{{entry.comments}}">{{ entry.comments|truncatewords:12 }}</td>
            <td><a href="{% url 'delete_invoice_entry' invoice.pk entry.pk %}">Remove</a></td>
        </tr>
    {% endfor %}
</table>

timepiece/templates/timepiece/invoice/_invoice.html
{% load timepiece_tags %}

<table class='table table-bordered'>
    {% if invoice.number %}
        <tr>
            <th>Number:</th>
            <td>{{ invoice.number }}</td>
        </tr>
    {% endif %}
    <tr>
        <th>Project:</th>
        <td>{{ invoice.project.name }}</td>
    </tr>
    <tr>
        <th>Status:</th>
        <td>{{ invoice.get_status_display }}</td>
    </tr>
    <tr>
        <th>Created by:</th>
        <td>{{ invoice.user.get_name_or_username }}</td>
    </tr>
    <tr>
        <th>Created on:</th>
        <td>{{ invoice.created|date:'M j, Y P' }}</td>
    </tr>
    <tr>
        <th>Last modified:</th>
        <td>{{ invoice.modified|date:'M j, Y P' }}</td>
    </tr>

    {% if invoice.start %}
        <tr>
            <th>Starting on:</th>
            <td>{{ invoice.start|date|default:"Not specified" }}</td>
        </tr>
    {% endif %}
    <tr>
        <th>Ending on:</th>
        <td>{{ invoice.end|date:'M j, Y'}}</td>
    </tr>
    {% if invoice.comments %}
        <tr>
            <th>Comments:</th>
            <td>{{ invoice.comments }}</td>
        </tr>
    {% endif %}
</table>

timepiece/templates/timepiece/invoice/_subnav.html
<h2>
    {% if current == 'edit' %}
        Edit Invoice for
    {% endif %}
    {% if current == 'entries' %}
        Entries for invoice of
    {% endif %}
    {% if current == 'detail' %}
        Invoice Details for
    {% endif %}

    {{ invoice.project.name }} hours
    {% if invoice.start %}
        from {{ invoice.start }} to {{ invoice.end }}
    {% else %}
        through {{ invoice.end }}
    {% endif %}
</h2>
<ul class="nav nav-pills">
    <li>
        <a href="{% url 'list_outstanding_invoices' %}">Outstanding Hours</a>
    </li>
    <li>
        <a href="{% url 'list_invoices' %}">Previous Invoices</a>
    </li>
    <li>
        {% if current != 'detail' %}
            <a href="{% url 'view_invoice' invoice.id %}">View Invoice</a>
        {% else %}
            <span>View Invoice</span>
        {% endif %}
    </li>
    <li>
        {% if current != 'edit' %}
            <a href="{% url 'edit_invoice' invoice.id %}">Edit Invoice</a>
        {% else %}
            <span>Edit Invoice</span>
        {% endif %}
    </li>
    <li>
        {% if current != 'entries' %}
            <a href="{% url 'view_invoice_entries' invoice.id %}">View Entries</a>
        {% else %}
            <span>View Entries</span>
        {% endif %}
    </li>
    <li>
        <a href="{% url 'view_invoice_csv' invoice.id %}">Download CSV</a>
    </li>
</ul>

timepiece/templates/timepiece/invoice/_totals.html
{% load timepiece_tags %}
<table class="table table-bordered">
    <tr>
        <th>Activity Type</th>
        <th>Total Hours</th>
    </tr>
    {% for name, hours_activities in totals %}
        <tr class="ledger_header">
            <th>{{ name|title }}</th>
            <td class="hours"> {{ hours_activities.0|floatformat:2  }} </td>
        </tr>
        {% for name, hours in hours_activities.1 %}
            <tr>
                <td>{{ name|title }}</td>
                <td class="hours">{{ hours|floatformat:2 }} </td>
            </tr>
        {% endfor %}
    {% endfor %}
</table>

timepiece/templates/timepiece/invoice/_weekly_entry_list.html
{% if billable_entries %}
    {% with entries=billable_entries %}
        <h4>Billable entries</h4>
        {% include 'timepiece/invoice/_weekly_entry_list_table.html' %}
    {% endwith %}
{% else %}
    <p>No billable entries were found.</p>
{% endif %}
{% if nonbillable_entries %}
    {% with entries=nonbillable_entries %}
        <h4>Non-billable entries</h4>
        {% include 'timepiece/invoice/_weekly_entry_list_table.html' %}
    {% endwith %}
{% else %}
    <p>No non-billable entries were found.</p>
{% endif %}

timepiece/templates/timepiece/invoice/_weekly_entry_list_table.html
{% load timepiece_tags %}
<table class="table table-bordered table-condensed table-striped">
    <thead>
    <tr>
        <th>Date</th>
        <th>User</th>
        <th>Time</th>
        <th>Project</th>
        <th>Activity</th>
        <th>Hours</th>
        <th>Comments</th>
    </tr>
    </thead>
    <tbody>
    {% for entry in entries %}
        {% ifchanged entry.start_time|date:"W" %}
            <tr class="ledger_header">
                <th colspan='7'>Week of {{ entry.start_time|week_start|date }} </th>
            </tr>
        {% endifchanged %}
        <tr>
            {% ifchanged entry.start_time|date %}
                <td>{{ entry.start_time|date:"m/d/Y (D)" }}</td>
            {% else %}
                <td></td>
            {% endifchanged %}
            <td>{{ entry.user.get_name_or_username }} </td>
            <td>{{ entry.start_time|time }} - {{ entry.end_time|time }} </td>
            <td>{{ entry.project.name }}</td>
            <td>{{ entry.activity.name }}</td>
            <td class="hours">{{ entry.hours|floatformat:"2" }}</td>
            <td title="{{entry.comments}}">{{ entry.comments|truncatewords:12 }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

timepiece/templates/timepiece/invoice/adjustment_create_edit.html
{% extends 'timepiece/invoice/base.html' %}
{% load bootstrap_toolkit %}
{% load url from future %}

{% block title %}{% if object %}Update{% else %}Create{% endif %} Invoice Adjustment{% endblock title %}

{% block crumbs %}
    {{ block.super }}
    {% if object %}
        <li><span class="divider">/</span> <a href="{% url 'edit_invoice_adjustment' invoice.pk  object.pk %}">Update Invoice Adjustment</a></li>
    {% else %}
        <li><span class="divider">/</span> <a href="{% url 'add_invoice_adjustment' invoice.pk %}">Create Invoice Adjustment</a></li>
    {% endif %}
{% endblock crumbs %}

{% block content %}
    <div class="row-fluid">
        <div class="span12">
            <h2>{% if object %}Update{% else %}Create{% endif %} Invoice Adjustment for {{ invoice }}</h2>

            <br style="clear: both;" />

            <form class="form-horizontal" action="" method="post" accept-charset="utf-8">
                {% csrf_token %}
                {{ form|as_bootstrap:"horizontal" }}
                <div class="form-actions">
                    <input class="btn btn-primary" type='submit' name='submit' value='Save' />
                    <input class="btn" type='button' value='Cancel' onclick="history.back()" />
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

timepiece/templates/timepiece/invoice/base.html
{% extends 'timepiece/base.html' %}

{% block crumbs %}
    {{ block.super }}
    <li><span class="divider">/</span> <a href="{% url 'list_invoices' %}">Invoices</a></li>
{% endblock crumbs %}

timepiece/templates/timepiece/invoice/outstanding.html
{% extends 'timepiece/invoice/base.html' %}
{% load timepiece_tags %}
{% load bootstrap3 %}

{% block title %}Outstanding Hours{% endblock title %}

{% block crumbs %}
    {{ block.super }}
    <li><span class="divider">/</span> <a href="">Outstanding Hours</a></li>
{% endblock crumbs %}

{% block content %}
    <div class="row-fluid">
        <div class="span12">
            <h2>Outstanding Hours</h2>
            <ul class="nav nav-pills">
                <li>
                    <span>Outstanding Hours</span>
                </li>
                {% if perms.contracts.view_entry_group %}  {# FIXME: Permission doesn't exist #}
                    <li>
                        <a href="{% url 'list_invoices' %}">Previous Invoices</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12">
            {% date_filters "date-filter" "months" 0 %}
        </div>
    </div>

    <div class="row-fluid">
        <div class="span4">
            <form class="form-horizontal" method="get" action="" id="date-filter" accept-charset="utf-8">
				{% bootstrap_form date_form layout='horizontal' field_class="controls" form_group_class="control-group" %}
                <div class="control-group">
                    <div class="controls">
                        <input class="btn btn-primary" type='submit' name='yearmonth' value="Update" id='yearmonth'/>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span6">
            {% if unverified %}
                <i class="icon-warning-sign"></i>
                <p><strong>Warning:</strong> The following users have <strong>unverified</strong> time during this period:</p>
                <ul>
                    {% for pk, first, last in unverified %}
                        <li>
                            <a href="{% user_timesheet_url pk from_date %}">{{ first }} {{ last }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
            {% if unapproved %}
                <i class="icon-warning-sign"></i>
                <p><strong>Warning:</strong> The following users have <strong>unapproved</strong> time during this period:</p>
                <ul>
                    {% for pk, first, last in unapproved %}
                        <li>
                            <a href="{% user_timesheet_url pk from_date %}">{{ first }} {{ last }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
            {% if not unverified and not unapproved %}
                <p>All time verified and approved</p>
            {% endif %}
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12">
            {# Display each project type as a separate table. #}
            {# For each table, order by project status, then business display name, then project name. #}
            {% regroup project_totals by project.type.label as type_list %}
            {% for type in type_list %}
                <h3>Summary of {{ type.grouper }} Entries</h3>

                <table class="table table-bordered table-condensed table-striped">
                    <thead>
                        <tr>
                            <th rowspan="2">Project</th>
                            <th rowspan="2">Active Contracts</th>
                            <th rowspan="2">Business</th>
                            <th rowspan="2">Status</th>
                            <th colspan="2">Uninvoiced Hours</th>
                            <th rowspan="2"></th>
                        </tr>
                        <tr>
                            <th>Billable</th>
                            <th>Non-billable</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% regroup type.list by project.name as project_list %}
                        {% for project in project_list %}
                            <tr>
                                <td><a href="{% project_timesheet_url project.list.0.project.pk to_date %}">{{ project.grouper }}</a></td>
                                <td>
                                    {# FIXME: This generates a db query for each project; can we make it faster? #}
                                    {% for contract in project.list.0.project.get_active_contracts %}
                                        <a href="{{ contract.get_absolute_url }}">{{ contract.name }}</a>
                                        {% if not forloop.last %}<br />{% endif %}
                                    {% endfor %}
                                </td>
                                <td>
                                {{ project.list.0.project.business.get_display_name }}</td>
                                <td>{{ project.list.0.project.status.label|title }}</td>
                                <td class="hours">{% get_uninvoiced_hours project.list 'billable' %}</td>
                                <td class="hours">{% get_uninvoiced_hours project.list 'nonbillable' %}</td>
                                <td>
                                    {% if from_date %}
                                        <a href="{% url 'create_invoice' %}?project= {{ project.list.0.project.pk }}&to_date={{ to_date|date:'Y-m-d' }}&from_date={{ from_date|date:'Y-m-d' }}">Make Invoice</a>
                                    {% else %}
                                        <a href="{% url 'create_invoice' %}?project={{ project.list.0.project.pk }}&to_date={{ to_date|date:'Y-m-d' }}">Make Invoice</a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% empty %}
                <p>There are no outstanding hours which match your filter criteria.</p>
            {% endfor %}
        </div>
    </div>
{% endblock content %}