timepiece/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    # Redirect the base URL to the dashboard.
    url(r'^$', RedirectView.as_view(url=reverse_lazy('dashboard'), permanent=False)),

    url('', include('timepiece.crm.urls')),
    url('', include('timepiece.contracts.urls')),
    url('', include('timepiece.entries.urls')),
    url('', include('timepiece.reports.urls')),
]

timepiece/crm/models.py
from collections import OrderedDict

from django.apps import apps
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models

from timepiece.utils import get_active_entry


# Add a utility method to the User class that will tell whether or not a
# particular user has any unclosed entries
_clocked_in = lambda user: bool(get_active_entry(user))
User.add_to_class('clocked_in', property(_clocked_in))


# Utility method to get user's name, falling back to username.
_get_name_or_username = lambda user: user.get_full_name() or user.username
User.add_to_class('get_name_or_username', _get_name_or_username)


_get_absolute_url = lambda user: reverse('view_user', args=(user.pk,))
User.add_to_class('get_absolute_url', _get_absolute_url)


class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True, related_name='profile', on_delete=models.deletion.CASCADE)
    hours_per_week = models.DecimalField(
        max_digits=8, decimal_places=2, default=40)

    class Meta:
        db_table = 'timepiece_userprofile'  # Using legacy table name.

    def __str__(self):
        return self.user


class TypeAttributeManager(models.Manager):
    """Object manager for type attributes."""

    def get_queryset(self):
        qs = super(TypeAttributeManager, self).get_queryset()
        return qs.filter(type=Attribute.PROJECT_TYPE)


class StatusAttributeManager(models.Manager):
    """Object manager for status attributes."""

    def get_queryset(self):
        qs = super(StatusAttributeManager, self).get_queryset()
        return qs.filter(type=Attribute.PROJECT_STATUS)


class Attribute(models.Model):
    PROJECT_TYPE = 'project-type'
    PROJECT_STATUS = 'project-status'
    ATTRIBUTE_TYPES = OrderedDict((
        (PROJECT_TYPE, 'Project Type'),
        (PROJECT_STATUS, 'Project Status'),
    ))
    SORT_ORDER_CHOICES = [(x, x) for x in range(-20, 21)]

    type = models.CharField(max_length=32, choices=ATTRIBUTE_TYPES.items())
    label = models.CharField(max_length=255)
    sort_order = models.SmallIntegerField(
        null=True, blank=True, choices=SORT_ORDER_CHOICES)
    enable_timetracking = models.BooleanField(
        default=False,
        help_text=('Enable time tracking functionality for projects '
                   'with this type or status.'))
    billable = models.BooleanField(default=False)

    objects = models.Manager()
    types = TypeAttributeManager()
    statuses = StatusAttributeManager()

    class Meta:
        db_table = 'timepiece_attribute'  # Using legacy table name.
        unique_together = ('type', 'label')
        ordering = ('sort_order',)

    def __str__(self):
        return self.label


class Business(models.Model):
    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=255, blank=True)
    email = models.EmailField(blank=True)
    description = models.TextField(blank=True)
    notes = models.TextField(blank=True)
    external_id = models.CharField(max_length=32, blank=True)

    class Meta:
        db_table = 'timepiece_business'  # Using legacy table name.
        ordering = ('name',)
        verbose_name_plural = 'Businesses'

    def __str__(self):
        return self.get_display_name()

    def get_absolute_url(self):
        return reverse('view_business', args=(self.pk,))

    def get_display_name(self):
        return self.short_name or self.name


class TrackableProjectManager(models.Manager):

    def get_queryset(self):
        return super(TrackableProjectManager, self).get_queryset().filter(
            status__enable_timetracking=True,
            type__enable_timetracking=True,
        )


class Project(models.Model):
    name = models.CharField(max_length=255)
    tracker_url = models.CharField(
        max_length=255, blank=True, null=False, default="")
    business = models.ForeignKey(
        Business, related_name='new_business_projects', on_delete=models.deletion.CASCADE)
    point_person = models.ForeignKey(User, limit_choices_to={'is_staff': True}, on_delete=models.deletion.CASCADE)
    users = models.ManyToManyField(
        User, related_name='user_projects', through='ProjectRelationship')
    activity_group = models.ForeignKey(
        'entries.ActivityGroup', related_name='activity_group', null=True,
        blank=True, verbose_name='restrict activities to', on_delete=models.deletion.CASCADE)
    type = models.ForeignKey(
        Attribute, limit_choices_to={'type': 'project-type'},
        related_name='projects_with_type', on_delete=models.deletion.CASCADE)
    status = models.ForeignKey(
        Attribute, limit_choices_to={'type': 'project-status'},
        related_name='projects_with_status', on_delete=models.deletion.CASCADE)
    description = models.TextField()

    objects = models.Manager()
    trackable = TrackableProjectManager()

    class Meta:
        db_table = 'timepiece_project'  # Using legacy table name.
        ordering = ('name', 'status', 'type',)
        permissions = (
            ('email_project_report', 'Can email project report'),
            ('view_project_time_sheet', 'Can view project time sheet'),
            ('export_project_time_sheet', 'Can export project time sheet'),
            ('generate_project_invoice', 'Can generate project invoice'),
        )

    def __str__(self):
        return '{0} ({1})'.format(self.name, self.business.get_display_name())

    @property
    def billable(self):
        return self.type.billable

    def get_absolute_url(self):
        return reverse('view_project', args=(self.pk,))

    def get_active_contracts(self):
        """Returns all associated contracts which are not marked complete."""
        ProjectContract = apps.get_model('contracts', 'ProjectContract')
        return self.contracts.exclude(status=ProjectContract.STATUS_COMPLETE)


class RelationshipType(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255)

    class Meta:
        db_table = 'timepiece_relationshiptype'  # Using legacy table name.

    def __str__(self):
        return self.name


class ProjectRelationship(models.Model):
    types = models.ManyToManyField(
        RelationshipType, blank=True, related_name='project_relationships')
    user = models.ForeignKey(User, related_name='project_relationships', on_delete=models.deletion.CASCADE)
    project = models.ForeignKey(Project, related_name='project_relationships', on_delete=models.deletion.CASCADE)

    class Meta:
        db_table = 'timepiece_projectrelationship'  # Using legacy table name.
        unique_together = ('user', 'project')

    def __str__(self):
        return "{project}'s relationship to {user}".format(
            project=self.project.name,
            user=self.user.get_name_or_username(),
        )

timepiece/templates/timepiece/project/approve_milestones.html
{% extends "timepiece/project/base.html" %}
{% load url from future %}
{% load timepiece_tags bootstrap_toolkit %}

{% block title %}{{ object }}{% endblock title %}

{% block crumbs %}
    {{ block.super }}
    <li><span class="divider">/</span> <a href="{% url 'view_project' object.id %}">{{ object }}</a></li>
{% endblock crumbs %}

{% block content %}
    <div class="row-fluid">
        <div class="span12">
            <h2>{{ object }}</h2>
            <ul class="nav nav-pills">
            </ul>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <form id="approve-milestones" class="form-horizontal" action="" method="post" accept-charset="utf-8">
                <h3>Milestones Pending Approval for {{ object }}</h3>
                {% for milestone in object.pending_milestones %}
                <table class="table table-bordered">
                    <tr><th>Name</th><td>{{ milestone.name }}</td></tr>
                    <tr><th>Due Date</th><td>{{ milestone.due_date|date:"M j, Y" }}</td></tr>
                    <tr><th>Description</th><td>{{ milestone.description|linebreaks }}</td></tr>
                </table>
                {% endfor %}

                {% csrf_token %}
                {{ form|as_bootstrap:"horizontal" }}
                <div class="form-actions">
                    <input class="btn btn-success" type='submit' name='approve' value='Approve All' />
                    <input class="btn" type='button' value='Cancel' onclick='history.go(-1)' />
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

timepiece/templates/timepiece/project/base.html
{% extends "timepiece/base.html" %}

{% block crumbs %}
    {{ block.super }}
    <li><span class="divider">/</span> <a href="{% url 'list_projects' %}">Projects</a></li>
{% endblock crumbs %}

timepiece/templates/timepiece/project/create_edit.html
{% extends "timepiece/project/base.html" %}
{% load bootstrap3 %}

{% block crumbs %}
    {{ block.super }}
    <li>
        <span class="divider">/</span>
        {% if not object %}
            <a href="{% url 'create_project' %}">Create Project</a>
        {% else %}
            <a href="{% url 'edit_project' object.pk %}">Edit Project</a>
        {% endif %}
    </li>
{% endblock crumbs %}

{% block title %}{% if not object %}Create Project{% else %}Edit {{ object }}{% endif %}{% endblock title %}

{% block content %}
    <div class="row-fluid">
        <div class="span12">
            <h2>{% if not object %}Create Project{% if business %} for {{ business }}{% endif %}{% else %}Edit {{ object }}{% endif %}</h2>

            <br style="clear: both;" />

            <form id="create-edit-project" class="form-horizontal" action="" method="post" accept-charset="utf-8">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' field_class="controls" form_group_class="control-group" %}
                <div class="form-actions">
                    <input class="btn btn-primary" type='submit' name='submit' value='Save' />
                    <input class="btn" type='button' value='Cancel' onclick='history.go(-1)' />
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

timepiece/templates/timepiece/project/list.html
{% extends "timepiece/project/base.html" %}
{% load bootstrap3 %}

{% block title %}Projects{% endblock title %}

{% block content %}
    <div class="row-fluid">
        <div class="span12">
            <h2>Projects</h2>
            <ul class="nav nav-pills">
            {% if perms.crm.add_project %}
                <li><a href='{% url 'create_project' %}'>Create Project</a></li>
            {% endif %}
            </ul>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12">
            <form class='form-inline' accept-charset='UTF-8' method='get' action=''>
                {% bootstrap_form form layout='inline' form_group_class="control-group" %}
                <button type='submit' class="btn" name='submit'>Search</button>
            </form>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12">
            {% include "timepiece/pagination.html" %}
            <table class='table table-striped table-bordered table-condensed'>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Business</th>
                        <th>Description</th>
                        <th>Time Sheet</th>
                    </tr>
                </thead>
                <tbody>
                    {% for project in object_list %}
                        <tr>
                            <td><a href="{% url 'view_project' project.id %}">{{ project.name }}</a></td>
                            <td>{{ project.business }}</td>
                            <td>{{ project.description|truncatewords:8 }}</td>
                            <td><a href="{% url 'view_project_timesheet' project.id %}">Time Sheet</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% include "timepiece/pagination.html" %}
        </div>
    </div>
{% endblock content %}

timepiece/templates/timepiece/project/timesheet.html
{% extends 'timepiece/project/base.html' %}
{% load timepiece_tags %}

{% block title %}{{ project }} - Time Sheet for {{ from_date|date:'M Y' }}{% endblock title %}

{% block crumbs %}
    {{ block.super }}
    <li><span class="divider">/</span> <a href="{% url 'view_project' project.pk %}">{{ project }}</a></li>
    <li><span class="divider">/</span> <a href="">Time Sheet</a></li>
{% endblock crumbs %}

{% block content %}
    <div class="row-fluid">
        <div class="span12">
            <h2>{{ project }} - Time Sheet for {{ from_date|date:'M Y' }}</h2>
            <ul class="nav nav-pills">
                <li><a href='{% url 'view_project' project.id %}'>Project Information</a></li>
            </ul>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12">
            <form class="form-inline" method="get" action="" id="date-filter" accept-charset="utf-8">
                {{ year_month_form }}
                <input class="btn" type='submit' name='yearmonth' value="Update" id='yearmonth'/>
                {% if perms.crm.export_project_time_sheet %}
                    <button class="btn" type='submit' name='csv' value="csv" id='csv'>Download CSV</button>
                {% endif %}
            </form>
        </div>
    </div>

    <div class="row-fluid">
        {% if user_entries %}
            <div class="span3">
                <table class='table table-bordered table-striped'>
                    <caption>User Summary</caption>
                {% for entry in user_entries %}
                    <tr>
                        <td>{{ entry.user__first_name }} {{ entry.user__last_name }}</td>
                        <td>{{ entry.sum }}</td>
                    </tr>
                {% endfor %}
                </table>
            </div>
        {% endif %}

        {% if activity_entries %}
            <div class="span3">
                <table class='table table-bordered table-striped'>
                    <caption>Activity Summary</caption>
                {% for entry in activity_entries %}
                    <tr>
                        <td>{{ entry.activity__name }}</td>
                        <td>{{ entry.sum }}</td>
                    </tr>
                {% endfor %}
                </table>
            </div>
        {% endif %}
    </div>


    <div class="row-fluid">
        <div class="span12">
            {% if entries %}
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Date</th>
                        <th>User</th>
                        <th>Activity</th>
                        <th>Location</th>
                        <th>Time In</th>
                        <th>Time Out</th>
                        <th>Breaks</th>
                        <th>Hours</th>
                        <th>Comments</th>
                    </tr>
                    {% for entry in entries %}
                    <tr{% if entry.comments %} title='{{ entry.comments }}'{% endif %}>
                        <td>{{ entry.start_time|date:"m/d/Y (D)" }}</td>
                        <td>{{ entry.user__first_name }} {{ entry.user__last_name }}</td>
                        <td>{{ entry.activity__name }}</td>
                        <td>{{ entry.location__name }}</td>
                        <td>{{ entry.start_time|time }}</td>
                        <td>{{ entry.end_time|time }}</td>
                        <td>{{ entry.seconds_paused|seconds_to_hours }}</td>
                        <td>{{ entry.hours }}</td>
                        <td title="{{entry.comments}}">{{ entry.comments|truncatewords:12 }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan='7'>Total:</th>
                        <td>{{ total|floatformat:2 }}</td>
                        <td></td>
                    </tr>
                </table>
            {% else %}
                <p>No entries exist for this time sheet.</p>
            {% endif %}
        </div>
    </div>
{% endblock content %}

timepiece/templates/timepiece/project/view.html
{% extends "timepiece/project/base.html" %}
{% load timepiece_tags bootstrap3 %}

{% block title %}{{ object }}{% endblock title %}

{% block crumbs %}
    {{ block.super }}
    <li><span class="divider">/</span> <a href="">{{ object }}</a></li>
{% endblock crumbs %}

{% block content %}
    <div class="row-fluid">
        <div class="span12">
            <h2>{{ object }}</h2>
            <ul class="nav nav-pills">
                {% if perms.crm.change_project %}
                    <li><a href="{% url 'edit_project' object.id %}">Edit</a></li>
                    <li><a href="{% url 'delete_project' object.id %}">Delete</a></li>
                {% endif %}
                {% if perms.crm.view_project_time_sheet %}
                    <li><a href="{% url 'view_project_timesheet' object.id %}">View Time Sheet</a></li>
                {% endif %}
                <li><a href="{% url 'report_hourly' %}?projects_1={{ object.id }}">View Hourly Report</a></li>
            </ul>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span6">
            <table class="table table-bordered">
                <tr><th>Type</th><td>{{ object.type }}</td></tr>
                <tr>
                    <th>Business</th>
                    <td>
                        {% if perms.crm.view_business  %}
                            <a href="{% url 'view_business' object.business.pk %}">{{ object.business }}</a>
                        {% else %}
                            {{ object.business }}
                        {% endif %}
                    </td>
                </tr>
                <tr><th>Status</th><td>{{ object.status }}</td></tr>
                <tr><th>Billable</th><td>{{ object.billable }}</td></tr>
                <tr>
                    <th>Point Person</th>
                    <td>
                        {% if perms.auth.view_user %}
                            <a href="{% url 'view_user' object.point_person.pk %}">{{ object.point_person.get_name_or_username }}</a>
                        {% else %}
                            {{ object.point_person.get_name_or_username }}
                        {% endif %}
                    </td>
                </tr>
                <tr><th>Description</th><td>{{ object.description|linebreaks }}</td></tr>
                {% if object.tracker_url %}
                    <tr><th>Tracker URL</th><td>{{ object.tracker_url }}</td></tr>
                {% endif %}
                <tr>
                    <th>Contracts</th>
                    <td>
                        {% for contract in object.contracts.all %}
                            <a href="{% url 'view_contract' contract.pk %}">{{ contract }}</a>
                            ({{ contract.start_date|date:'M j, Y'}} - {{ contract.end_date|date:'M j, Y'}})
                            <br />
                        {% empty %}
                            This project is not associated with any contracts.
                        {% endfor %}
                    </td>
                </tr>
            </table>
        </div>

        <div class="span4 offset2">
            {% url 'view_project' object.id as next_url %}
            <h3>Users</h3>
            <ul class="users">
                {% for user in object.users.all %}
                    <li>
                        {{ user.get_name_or_username }}
                        {% if perms.crm.change_projectrelationship %}
                            {% with caption="Edit "|add:user.get_name_or_username|add:"'s relationship to "|add:object.name %}
                                <a title="{{ caption }}" href="{% url 'edit_relationship' %}?project_id={{ object.id}}&user_id={{ user.id }}&next={{ next_url|add_parameters:request.GET|urlencode }}"><i alt="{{ caption }}" class="icon-pencil"></i></a>
                            {% endwith %}
                        {% endif %}
                        {% if perms.crm.delete_projectrelationship %}
                            {% with caption="Remove "|add:user.get_name_or_username|add:" from "|add:object.name %}
                                <a title="{{ caption }}" href="{% url 'delete_relationship' %}?project_id={{ object.id }}&user_id={{ user.id }}&next={{ next_url|add_parameters:request.GET|urlencode }}"><i alt="{{ caption }}" class="icon-remove"></i></a>
                            {% endwith %}
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
            {% if perms.crm.add_projectrelationship %}
                <form class="form-inline" action="{% url 'create_relationship' %}?project_id={{ object.id }}&next={{ next_url|add_parameters:request.GET|urlencode }}" method="post" accept-charset="utf-8">
                    {% csrf_token %}
                    {% bootstrap_form add_user_form layout='inline' form_group_class="control-group" %}
                    <input class="btn" type="submit" value="Add" />
                </form>
            {% endif %}
        </div>
    </div>
{% endblock content %}