timepiece/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    # Redirect the base URL to the dashboard.
    url(r'^$', RedirectView.as_view(url=reverse_lazy('dashboard'), permanent=False)),

    url('', include('timepiece.crm.urls')),
    url('', include('timepiece.contracts.urls')),
    url('', include('timepiece.entries.urls')),
    url('', include('timepiece.reports.urls')),
]

timepiece/forms.py
import datetime
from dateutil.relativedelta import relativedelta
import time
import calendar

from django import forms
from django.contrib.auth.models import User

from timepiece.fields import UserModelChoiceField

from timepiece.entries.models import Entry


DATE_FORM_FORMAT = '%Y-%m-%d'
INPUT_FORMATS = [DATE_FORM_FORMAT]


class TimepieceSplitDateTimeWidget(forms.SplitDateTimeWidget):

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('date_format', DATE_FORM_FORMAT)
        super(TimepieceSplitDateTimeWidget, self).__init__(*args, **kwargs)


class TimepieceSplitDateTimeField(forms.SplitDateTimeField):
    widget = TimepieceSplitDateTimeWidget


class TimepieceDateInput(forms.DateInput):

    def __init__(self, *args, **kwargs):
        kwargs['format'] = kwargs.get('format', DATE_FORM_FORMAT)
        super(TimepieceDateInput, self).__init__(*args, **kwargs)


class DateForm(forms.Form):
    from_date = forms.DateField(
        label='From', required=False, input_formats=INPUT_FORMATS,
        widget=TimepieceDateInput())
    to_date = forms.DateField(
        label='To', required=False, input_formats=INPUT_FORMATS,
        widget=TimepieceDateInput())

    def clean(self):
        from_date = self.cleaned_data.get('from_date', None)
        to_date = self.cleaned_data.get('to_date', None)
        if from_date and to_date and from_date > to_date:
            raise forms.ValidationError('The ending date must exceed the '
                                        'beginning date.')
        return self.cleaned_data

    def save(self):
        from_date = self.cleaned_data.get('from_date', '')
        to_date = self.cleaned_data.get('to_date', '')
        to_date = to_date + relativedelta(days=1) if to_date else to_date
        return (from_date, to_date)

class UserDateForm(DateForm):
    user = UserModelChoiceField(label='', queryset=None, required=False)

    def __init__(self, *args, **kwargs):
        super(UserDateForm, self).__init__(*args, **kwargs)
        queryset = User.objects.exclude(timepiece_entries=None)\
                               .order_by('first_name')
        self.fields['user'].queryset = queryset
        self.fields['to_date'].label = ''
        self.fields['to_date'].widget.attrs['placeholder'] = 'End Date'
        self.fields['from_date'].label = ''
        self.fields['from_date'].widget.attrs['placeholder'] = 'Start Date'

    def save(self):
        from_date, to_date = super(UserDateForm, self).save()
        return (from_date, to_date, self.cleaned_data.get('user', None))

class StatusDateForm(DateForm):
    status = forms.ChoiceField(label='', required=False)

    def __init__(self, *args, **kwargs):
        super(StatusDateForm, self).__init__(*args, **kwargs)
        self.fields['status'].choices = [('', 'All')] + Entry.STATUSES.items()

    def save(self):
        (from_date, to_date) = super(StatusDateForm, self).save()
        return (from_date, to_date, self.cleaned_data.get('status', None))

class StatusUserDateForm(UserDateForm):
    status = forms.ChoiceField(label='', required=False)

    def __init__(self, *args, **kwargs):
        super(StatusUserDateForm, self).__init__(*args, **kwargs)
        self.fields['status'].choices = [('', 'All')] + Entry.STATUSES.items()

    def save(self):
        (from_date, to_date, user) = super(StatusUserDateForm, self).save()
        return (from_date, to_date, user, self.cleaned_data.get('status', None))


class YearMonthForm(forms.Form):
    MONTH_CHOICES = [(i, time.strftime('%b', time.strptime(str(i), '%m')))
                     for i in xrange(1, 13)]
    #MONTH_CHOICES = sum([[(2*i-1, time.strftime('%b', time.strptime(str(i), '%m'))+' 1-15'), (2*i, time.strftime('%b', time.strptime(str(i), '%m'))+' 16-'+str(calendar.monthrange(datetime.datetime.now().year,i)[1]))] for i in xrange(1, 13)], [])
    month = forms.ChoiceField(choices=MONTH_CHOICES, label='')
    half = forms.ChoiceField(choices=[(1, '1st - 15th'), (2, '16th - end')], label='')
    year = forms.ChoiceField(label='')

    def __init__(self, *args, **kwargs):
        super(YearMonthForm, self).__init__(*args, **kwargs)
        now = datetime.datetime.now()
        this_year = now.year
        this_month = now.month
        this_half = 1 if datetime.datetime.now().day <= 15 else 2
        try:
            first_entry = Entry.no_join.values('end_time')\
                                       .order_by('end_time')[0]
        except IndexError:
            first_year = this_year
        else:
            first_year = first_entry['end_time'].year
        years = [(year, year) for year in range(first_year, this_year + 1)]
        self.fields['year'].choices = years
        initial = kwargs.get('initial')
        if initial:
            this_year = initial.get('year', this_year)
            this_month = initial.get('month', this_month)
            this_half = initial.get('half', this_half)
        self.fields['year'].initial = this_year
        self.fields['month'].initial = this_month
        self.fields['half'].initial = this_half

    def save(self):
        now = datetime.datetime.now()
        this_year = now.year
        this_month = now.month
        this_half = 1 if datetime.datetime.now().day <= 15 else 2
        month = int(self.cleaned_data.get('month', this_month))
        year = int(self.cleaned_data.get('year', this_year))
        half = int(self.cleaned_data.get('half', this_half))
        if half == 1:
            from_date = datetime.datetime(year, month, 1)
            to_date = datetime.datetime(year, month, 16)
        elif half == 2:
            from_date = datetime.datetime(year, month, 16)
            if month<12:
                to_date = datetime.datetime(year, month+1,1)
            else:
                to_date = datetime.datetime(year+1, 1,1)

        return (from_date, to_date)


class UserYearMonthForm(YearMonthForm):
    user = UserModelChoiceField(label='', queryset=None, required=False)

    def __init__(self, *args, **kwargs):
        super(UserYearMonthForm, self).__init__(*args, **kwargs)
        queryset = User.objects.exclude(timepiece_entries=None)\
                               .order_by('first_name')
        self.fields['user'].queryset = queryset

    def save(self):
        from_date, to_date = super(UserYearMonthForm, self).save()
        return (from_date, to_date, self.cleaned_data.get('user', None))

timepiece/templates/timepiece/time-sheet/_date_filters.html
<script type="text/javascript">
    function update_dates(node) {
        var from_date = $("#id_from_date");
        var to_date = $("#id_to_date");
        from_date.val($(node).attr("from_date"));
        to_date.val($(node).attr("to_date"));
        $("#{{ form_id }}").submit();
    };
</script>

<ul class="date-filters">
    {% for filter_category, filter_list in filters.iteritems %}
        <li>
            <ul>
                <li class="label">{{ filter_category }}</li>
                {% for label, from_date, to_date in filter_list %}
                    <li><a href="javascript:void(0);" class="date-filter" from_date="{{ from_date }}" to_date="{{ to_date }}" onclick="update_dates(this);">{{ label }}</a></li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
</ul>

timepiece/templates/timepiece/time-sheet/general_ledger.html
{% extends 'timepiece/time-sheet/base.html' %}
{% load timepiece_tags %}

{% block title %}Timepiece Entries{% endblock %}

{% block content %}
<h2>Time Tracking Report</h2>

<form action="" method="get" accept-charset="utf-8">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
</form>
<div style="float:left;padding:10px;">
<h3>Hours by Project</h3>

<br />
<table>
    {% for entry in project_totals %}
    <tr>
        <td><a href='{% url view_project entry.project__id %}'>{{ entry.project__name }}</a></td>
        <td>{{ entry.total_hours|floatformat:2 }}</td>
    </tr>
    {% endfor %}
    <tr>
        <th colspan='2'>&nbsp;</th>
    </tr>
    <tr>
        <th>Total:</th>
        <td>{{ total_hours|floatformat:2 }}</td>
    </tr>
</table>
</div>
<div style="float:left;padding:10px;">
<h3>Hours by People</h3>
<br />
<table>
    {% for entry in people_totals %}
    <tr>
        <td>{{ entry.user__first_name}} {{ entry.user__last_name }}</td>
        <td>{{ entry.total_hours|floatformat:2 }}</td>
    </tr>
    {% endfor %}
    <tr>
        <th colspan='2'>&nbsp;</th>
    </tr>
</table>
</div>
{% endblock %}

timepiece/templates/timepiece/time-sheet/invoice_project_confirm.html
{% extends 'timepiece/time-sheet/base.html' %}
{% load timepiece_tags %}
{% load url from future %}

{% block title %}Invoice Hours for Time Sheet{% endblock %}

{% block content %}
  <h2>Invoice {{ project.name }} Hours {% if from_date %}from {{ from_date.date }} to {{ to_date.date }}{% else %}through {{ to_date.date }}{% endif %}</h2>
  <br />
  <form method="post">{% csrf_token %}
      <table class='vertical'>
        {{ invoice_form }}
        <tr>
          <td>&nbsp;</td>
          <td class='submit'>
            <input type='button' value='Cancel' onclick='history.go(-1)' />
            &nbsp;
            <input type='submit' name='submit' value='Update Entries &rarr;' />
          </td>
        </tr>
      </table>
  </form>
<br />
<h3>Selected Entries</h3>
<table class="time-sheet">    
    <tr>
        <th>Date</th>
        <th>User</th>
        <th>Time</th>
        <th>Project</th>
        <th>Activity</th>
        <th>Hours</th>
        <th>Comments</th>
    </tr>            
    {% for entry in entries %}
        {% ifchanged entry.start_time|date:"W" %}
            <tr class="ledger_header">
                <th colspan='7'>Week of {% week_start entry.start_time %} </th>
            </tr>
        {% endifchanged %}
        <tr>
            {% ifchanged entry.start_time|date %}
                <td>{{ entry.start_time|date:"m/d/Y (D)" }}</td>
            {% else %}
                <td></td>
            {% endifchanged %}
        <td>{{ entry.user.get_full_name }} </td>
        <td>{{ entry.start_time|date:"P" }} - {{ entry.end_time|date:"P" }} </td>
        <td>{{ entry.project.name }}</td>
        <td>{{ entry.activity.name }}</td>
        <td class="hours">{{ entry.hours }}</td>
        <td title="{{entry.comments}}">{{ entry.comments|truncatewords:12 }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

timepiece/templates/timepiece/time-sheet/invoice_projects.html
{% extends 'timepiece/time-sheet/base.html' %}
{% load timepiece_tags %}
{% load url from future %}

{% block title %}Project Invoice Summary{% endblock %}

{% block content %}
<h2>Project Invoice Summary</h2>
{% date_filters "months_no_range" %}
<form method="get" action="" id="date-filter" accept-charset="utf-8">
    {{ date_form }}
    <input type='submit' name='yearmonth' value="Update" id='yearmonth'/>
</form>

<div class="cal_wrapper" style='float: right;'>
    <div class="cal left"> {% show_cal to_date -1 %} </div>
    <div class="cal middle"> {% show_cal to_date 0 %} </div>
</div>

{% if unverified %}
    <p><strong>Warning:</strong> The following users have <strong>unverified</strong> time during this period:</p>
    <ul>
        {% for pk, first, last in unverified %}
            <li><a href="{% url 'view_person_time_sheet' pk %}">{{ first }} {{ last }}</a></li>
        {% endfor %}
    </ul>
{% endif %}

{% if unapproved %}
    <p><strong>Warning:</strong> The following users have <strong>unapproved</strong> time during this period:</p>
    <ul>
        {% for pk, first, last in unapproved %}
            <li><a href="{% url 'view_person_time_sheet' pk %}">{{ first }} {{ last }}</a></li>
        {% endfor %}
    </ul>
{% endif %}

{% regroup project_totals by project__type__label as type_list %}
{% for type in type_list %}
    <h3>Summary of {{ type.grouper }} Entries</h3>
    <table>
        <tr>
            <th>Project name</th>
            <th>Status</th>
            <th>Uninvoiced Hours</th>
            <th></th>
        </tr>
        {% regroup type.list by project__name as project_list %}
        {% for project in project_list %}
            <tr>
                <th>{{ project.grouper }}</th>
                <td>{{ project.list.0.project__status__label|title }}</td>
                {% build_invoice_row project.list to_date from_date %}
            </tr>
        {% endfor %}
    </table>
{% endfor %}
{% endblock %}